#->	UNCOMMENT ANY LINES YOU WISH TO CHANGE, AND MAKE YOUR CHANGES.
#->	ALL OF THE BELOW DEFAULTS ARE SET IN THE MAKEFILE BEFORE CALLING
#->	ON THIS FILE TO REPLACE THE VALUES DESIRED BY THE USER.

#REGISTRY_HOST=docker.io
#USERNAME=$(USER)
#NAME=$(shell basename $(CURDIR))

#RELEASE_SUPPORT := $(shell dirname $(abspath $(lastword $(MAKEFILE_LIST))))/.make-release-support
#IMAGE=$(REGISTRY_HOST)/$(USERNAME)/$(NAME)

#VERSION=$(shell . $(RELEASE_SUPPORT) ; getVersion)
#TAG=$(shell . $(RELEASE_SUPPORT); getTag)

#SHELL=/bin/bash

#DOCKER_BUILD_CONTEXT=.
#DOCKER_FILE_PATH=Dockerfile
