path=../make/
config=../config.mk

#-> INSERT PROJECT-SPECIFIC CONFIG CHANGES HERE

include $(path)Makefile

pre-build:
	@echo do some stuff before the docker build

post-build:
	@echo do some stuff after the docker build

